### ISSUE TITLE
NIST 800-53 JSON Profiles Link to XML Catalogs

### ISSUE THREAD

**Issue by rgauss** [usnistgov/oscal-content#59] opened 2021-03-19 13:55 UTC
# Describe the bug

The NIST 800-53 [JSON profiles contain back-matter links to XML catalogs](https://github.com/usnistgov/oscal-content/blob/master/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_MODERATE-baseline_profile.json#L3087) rather than the JSON representation, even though the [`media-type` indicates json](https://github.com/usnistgov/oscal-content/blob/master/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_MODERATE-baseline_profile.json#L3088).

# Who is the bug affecting?

Developers attempting to resolve catalogs from JSON profiles

# What is affected by this bug?

The ability to parse the proper catalog

# When does this occur?

Always

# How do we replicate the issue?

Attempt to resolve a catalog from a profile using JSON tooling

# Expected behavior (i.e. solution)

The `rlink` should reference the JSON representation of the catalog

# Other Comments

**Comment by david-waltermire-nist** [comment] 2021-05-20 14:52
@rgauss This is caused by a broken approach to content conversion in the XML <-> JSON/YAML conversion pipelines. We have some ideas on how to fix this properly.

Until we can put in place an automated approach, it isn't possible to fix this. We will make this a priority after OSCAL v1.0.0 is released.

**Comment by aj-stein-nist** [comment] 2022-01-22 04:08
The code has been merged but we need to update the relevant git submodule to the proper commit when we finalize [the `v1.0.1` release](https://github.com/usnistgov/OSCAL/milestone/12) and can point to the submodule formally once it is wrapped up.

**Closed** 2022-01-30 16:52 UTC
Labels: bug
