### ISSUE TITLE
Erroneous self-reference on SC-12

### ISSUE THREAD

**Issue by Agh42** [usnistgov/oscal-content#72] opened 2021-05-10 07:18 UTC
# Describe the bug

In _NIST_SP-800-53_rev5_catalog.json_ there is a self-reference from control SC-12 to SC-12 (itself).

# Who is the bug affecting?

Everyone working with the example catalog.

# What is affected by this bug?

Data consistency.

# When does this occur?

When importing the data into a tool.

# How do we replicate the issue?

Please see the attached screenshots:

* I highlighted the link in the JSON file.
* I noticed the self-reference while importing this data into the Neo4J graph database. It's immediately obvious in the graph:

![Bildschirmfoto von 2021-05-10 09-07-11](https://user-images.githubusercontent.com/7584303/117620051-59718f00-b170-11eb-9b37-a54c732fe6cd.png)

![Bildschirmfoto von 2021-05-10 09-02-57](https://user-images.githubusercontent.com/7584303/117620078-62faf700-b170-11eb-8137-f758e2e50cfe.png)

# Expected behavior (i.e. solution)

This reference should not be present.

# Other Comments

I noticed this while importing the OSCAL content into a Neo4J database. The scripts I am using are available in my [Github repo](https://github.com/Agh42/comply-22/tree/main/data/NIST-800-53/script)

**Comment by wendellpiez** [comment] 2021-05-11 14:24
Thank you @Agh42 I have confirmed we have two of these in both XML and JSON representations: *SC-12* refers to itself and so does *PS-6*.

However, I can't confirm that this is an error since the published catalog (I looked at https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf) also shows these controls with references to themselves. (So: while quite probably an error, I am not the one to say.)

This means the error is in the upstream sources, and probably in the current FISMA database.

We probably need to bring this to the FISMA team to clarify the intent here, and then refresh on their revision cycle.

Good find!

**Comment by wendellpiez** [comment] 2022-03-03 14:56
@david-waltermire-nist this is a good example of a FISMA team issue.

**Comment by david-waltermire-nist** [comment] 2022-03-22 15:57
@Agh42 We have committed to keep the OSCAL content in sync with the published SP 800-53 content. Once this is fixed in the SP 800-53 content, we will get the updated OSCAL to fix this. Until then, we cannot do much about this.

**Comment by wendellpiez** [comment] 2023-02-01 20:55
My current upstream dataset shows this fixed. Presumably a change will show up in a diff in the (eventual) PR.

It's kind of fun how this data issue shows up when a robot draws a picture. I'm a little surprised there were not more. Speaks to the thoroughness and care of the data owners.

**Comment by aj-stein-nist** [comment] 2023-02-01 21:39
> My current upstream dataset shows this fixed. Presumably a change will show up in a diff in the (eventual) PR.

Cool, can we commit to cutting it out of your current dataset into a targeted PR to fix this? I will remove the closable tag for now.

> It's kind of fun how this data issue shows up when a robot draws a picture. I'm a little surprised there were not more. Speaks to the thoroughness and care of the data owners.

Yes, we need to make it an important, long-term priority to find ways of detecting such issues early, but that will come later. Thanks.

**Comment by wendellpiez** [comment] 2023-02-02 00:16
Actually no. The change was actually a change that had to be made to upstream content. (We communicated it to data owners and they made the change.) So it's going to come in with other revisions that come with this update. This makes it effectively impossible to carve out.

Your final remark suggests you don't get the point though. The error was not ours, nor was the redundant link. SC-12 actually did refer to itself and the link was an accurate reflection. Only with the forthcoming errata update will it be fixed - not because we fixed it, but because it was deemed an erratum. 😎

**Comment by aj-stein-nist** [comment] 2023-02-02 00:34
> Your final remark suggests you don't get the point though.

Can you set aside 15 minutes to meet with me and it explain it then? Thanks.

**Comment by wendellpiez** [comment] 2023-02-02 14:14
The point is that this is not the kind of "error" we can detect, since it is not an error until it is defined as such in the source data we are bound to emulate, by the owners of that source data.

Sorry if the tone was short - it was late, last night.

**Comment by wendellpiez** [comment] 2023-02-06 17:32
Okay.

To summarize:
1. The original report was not an OSCAL error, it was an error in the original document. Control SC-12 contains a link to itself among its 'related' controls.
2. Thanking our user for detecting it, we reported this to the FISMA team.
3. It will be resolved in the forthcoming rev5.2 update release.
4. While arguably we could remove the offending link prior to this, to do so violates our contract of fidelity to the source.

In view of this, what remains to be done on this Issue? Once FISMA made the delivery, it will disappear when we commit the updated OSCAL.

Happy to fit in the 15 or 30.

**Comment by iMichaela** [comment] 2024-01-16 22:56
CPRT shows that this error documented in this issue has been fixed in the 800-53 v 5.1.1 but not in OSCAL representation. We will be able to fix the error in OSCAL version as well.

**Comment by iMichaela** [comment] 2024-02-02 12:58
Addressed by #238

**Closed as completed** 2024-02-02 12:59 UTC
Labels: bug
