### ISSUE TITLE
Relative Profile Import of the Example SSP is Incorrect

### ISSUE THREAD

**Issue by rgauss** [usnistgov/oscal-content#60] opened 2021-03-19 14:16 UTC
# Describe the bug

The example SSP contains a [relative `import-profile` `href`](https://github.com/usnistgov/oscal-content/blob/master/examples/ssp/json/ssp-example.json#L44) that is incorrect.  (I believe the profiles were moved and the relative links weren't updated.

# Who is the bug affecting?

Developers trying to resolve the example SSP's profile

# What is affected by this bug?

The example SSP's profile

# When does this occur?

Always

# How do we replicate the issue?

Attempt to resolve the example SSP's profile

# Expected behavior (i.e. solution)

The `import-profile` `href` should point to the correct profile location

# Other Comments

**Comment by iMichaela** [comment] 2021-04-05 20:12
@rgauss and @david-waltermire-nist - If the file you are referring to is under the `oscal-content/src/...ssp/json/ssp_example.jon`, please note that all files in the `src` directory are used to automatically generate the examples in the `examples` directory. In the `examples` directory the relative path `../../nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_MODERATE-baseline_profile.json` appears correct to me. If I am missing something, please let me know and I can fix it in the existing PR.  If the *bug* is reporting the wrong path in the file under  the `src` directory, then this is not a bug, and I suggest closing this issue.

**Comment by david-waltermire-nist** [comment] 2021-04-05 20:57
@rgauss and @iMichaela I believe the correct link should be `../../../nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_MODERATE-baseline_profile.json`.

We are doing some path rewriting as part of the XML, JSON, and YAML conversion process. I'll fix this in the source and confirm that the path rewriting is working correctly in the generated files.

**Comment by iMichaela** [comment] 2021-04-05 22:27
@david-waltermire-nist Right!  my bad.  I found similar issue with the relative path in the two leveraged authorization examples. I corrected them all in the PR #63 .

**Closed** 2021-04-12 20:09 UTC
Labels: bug
